version: "3"

services:
    app:
        image: ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_PIPELINE_ID}
        env:
          - "ELASTIC_APM_SERVER_URL:http://172.16.77.209:8200"
        deploy:
            replicas: 1
            restart_policy:
                condition: any
                max_attempts: 3
            placement:
                constraints: [node.labels.worker == true]
            labels:
                - traefik.backend=${DEV_ENV}-${CI_PROJECT_NAME}
                - traefik.frontend.rule=PathPrefix:/v2/passenger/ride/{id}/driver-location;Host:base-api.${DEV_ENV}.snapp.tech
                - traefik.docker.network=traefik
                - traefik.port=9999
        networks:
            - internal
            - traefik

    app-debug:
        image: ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_PIPELINE_ID}
        deploy:
            replicas: 1
            restart_policy:
                condition: any
                max_attempts: 3
            placement:
                constraints: [node.labels.worker == true]
            labels:
                - traefik.backend=${DEV_ENV}-${CI_PROJECT_NAME}-debug
                - traefik.frontend.rule=PathPrefix:/debug/vars;Host:${CI_PROJECT_NAME}.${DEV_ENV}.snapp.tech
                - traefik.docker.network=traefik
                - traefik.port=9999
        networks:
            - internal
            - traefik

networks:
  traefik:
    external: true
  internal:
    external: false

