version: "3"

services:
    app:
        image: ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_PIPELINE_ID}
        environment:
          ELASTIC_APM_SERVER_URL: "http://172.16.77.209:8200"
        deploy:
            replicas: 1
            restart_policy:
                condition: any
                max_attempts: 3
            placement:
                constraints: [node.labels.worker == true]
            labels:
                - traefik.backend=${DEV_ENV}-${CI_PROJECT_NAME}
                - traefik.frontend.rule=PathPrefix:/hello;Host:elastest.${DEV_ENV}.snapp.tech
                - traefik.docker.network=traefik
                - traefik.port=9999
        networks:
            - internal
            - traefik

networks:
  traefik:
    external: true
  internal:
    external: false

